# Generated by Django 4.0.3 on 2022-03-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40)),
                ('conten_post', models.CharField(max_length=5000)),
                ('autor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Reseta',
            fields=[
                ('nombre', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('queso', models.CharField(max_length=40)),
                ('condimentos', models.CharField(max_length=20)),
                ('relleno', models.CharField(max_length=40)),
                ('salsa', models.CharField(max_length=40)),
                ('carne', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Users_login',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
