# Generated by Django 4.0.3 on 2022-04-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users_login',
        ),
    ]
