# Generated by Django 4.0.3 on 2022-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_reseta_id_alter_reseta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conten_post',
            field=models.TextField(),
        ),
    ]
