# Generated by Django 4.0.3 on 2022-04-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mensajeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=40)),
                ('receptor', models.CharField(max_length=40)),
                ('asunto', models.CharField(max_length=60)),
                ('cuerpo', models.CharField(max_length=5000)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
