# Generated by Django 4.0.3 on 2022-04-21 21:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajeria',
            name='cuerpo',
        ),
        migrations.AddField(
            model_name='mensajeria',
            name='conten_post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
