# Generated by Django 4.0.3 on 2022-04-16 23:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apppost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conten_post',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Imagenpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apppost.post')),
            ],
        ),
    ]
