# Generated by Django 4.0.3 on 2022-04-17 01:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppost', '0002_alter_post_conten_post_imagenpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conten_post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/post'),
        ),
    ]
